
# 运行模式(debug:调试,test:测试,release:正式)
runmode = "debug"

# 是否启用swagger
swagger = false

# 启动时是否打印配置参数
printconfig = false

[casbin]
enable = true

[http]
port = 80
contextpath = "/api/ka/v1"

[jwtauth]
signingsecret = "J928KDD"
limittime = 5 # 秒

[mysql]
host = "192.168.3.123"
port = 3306
user = "123"
password = "123"
dbname = "zgo1"
parameters = "charset=utf8&parseTime=True&loc=Asia%2FShanghai"

[mysql2]
host = "192.168.3.123"
port = 3306
user = "123"
password = "123"
dbname = "zgo2"
parameters = "charset=utf8&parseTime=True&loc=Asia%2FShanghai"

[i18n]
dbenable = false